/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Fab: typeof import('./components/Fab/Fab.vue')['default']
    FabContainer: typeof import('./components/Fab/FabContainer.vue')['default']
    FabItem: typeof import('./components/Fab/fabItem.vue')['default']
    Layout: typeof import('./components/Layout.vue')['default']
  }
}
